// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: itmatrixhq/rest/v1/wire.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "itmatrixhq.rest.v1";

/**
 * itmatrixhq.rest.v1 — PUBLIC protobuf bodies for negotiated REST responses.
 *
 * External SDKs request these with Accept: application/x-protobuf on the
 * high-volume reads (bars / replay / gex grid / chain); JSON remains the
 * default. Errors stay JSON on every transport. Field conventions: scaled
 * sint32 prices (PRICE_SCALE = 10000), epoch-ms timestamps, absent = unset
 * (proto3 optional), strikes in thousandths.
 */

export interface BarsResponse {
  priceScale: number;
  completeThroughMs?: bigint | undefined;
  priorCloseScaled?: number | undefined;
  bars: Bar[];
  /** Opaque pagination cursor; presence means more data remains. */
  cursor: string;
}

export interface Bar {
  tsMs: bigint;
  o: number;
  h: number;
  l: number;
  c: number;
  v?: number | undefined;
  vwap?: number | undefined;
  n?: number | undefined;
}

export interface ReplayResponse {
  priceScale: number;
  /** 0 = ticks, 1 = bars1m */
  fidelity: number;
  complete: boolean;
  /** tick source names (fidelity = ticks) */
  sources: string[];
  ticks: Tick[];
  bars: Bar[];
}

export interface Tick {
  tsMs: bigint;
  priceScaled: number;
  sourceId: number;
  /** Monotonic per-symbol sequence (u64 — must not truncate). */
  seq: bigint;
}

/**
 * GEX values are dollars of dealer hedging per $1 move in the underlying.
 * Each `*_shares` field is its dollar sibling in shares of the underlying
 * per $1 move, absent when unknown.
 */
export interface GexGridResponse {
  capturedAtMs?: bigint | undefined;
  spot?: number | undefined;
  priorCloseSpot?: number | undefined;
  netGex: number;
  netGexShares?: number | undefined;
  flipPoint?: number | undefined;
  maxAbsGex: number;
  maxAbsGexShares?: number | undefined;
  adhoc: boolean;
  rows: GexGridRow[];
}

export interface GexGridRow {
  strikeThousandths: bigint;
  gex: number;
  gexShares?: number | undefined;
  gex0dte?: number | undefined;
  gex0dteShares?: number | undefined;
  callOi?: number | undefined;
  putOi?: number | undefined;
  deltaAdj?: number | undefined;
  deltaAdjShares?: number | undefined;
  expiryEpochDay?: number | undefined;
}

export interface ChainResponse {
  capturedAtMs?: bigint | undefined;
  spot?: number | undefined;
  partial: boolean;
  rows: ChainRow[];
}

export interface ChainRow {
  expiryEpochDay: number;
  /** 0 = call, 1 = put */
  right: number;
  strikeThousandths: bigint;
  oi?: bigint | undefined;
  volume?: bigint | undefined;
  bid?: number | undefined;
  ask?: number | undefined;
  last?: number | undefined;
  fmv?: number | undefined;
  iv?: number | undefined;
  delta?: number | undefined;
  gamma?: number | undefined;
  theta?: number | undefined;
  vega?: number | undefined;
  sharesPerContract: number;
}

/**
 * Synthetic aggregates derived from ITMatrixHQ's locally captured
 * off-exchange feed. These messages intentionally have no raw-print identity,
 * venue/TRF, condition, or vendor-source fields.
 */
export interface OffExchangeActivityResponse {
  rows: OffExchangeActivityRow[];
}

export interface OffExchangeActivityRow {
  date: string;
  offExchangeVolume: number;
  notional: number;
  tradeCount: bigint;
  averageSize: number;
  vwap: number;
  offExchangeShare?: number | undefined;
  consolidatedVolume?: number | undefined;
  consolidatedNotional?: number | undefined;
}

export interface OffExchangeConcentrationResponse {
  rows: OffExchangeConcentrationRow[];
}

export interface OffExchangeConcentrationRow {
  date: string;
  bucketMidpoint: number;
  bucketWidth: number;
  volume: number;
  notional: number;
  tradeCount: bigint;
  distinctSessions: number;
  rankScore: number;
  rank: number;
  bucketCount: number;
  distanceBps?: number | undefined;
  lookbackSessions: number;
}

export interface OffExchangeProfileResponse {
  rows: OffExchangeProfileRow[];
}

export interface OffExchangeProfileRow {
  date: string;
  priceThousandths: bigint;
  volume: number;
  notional: number;
  tradeCount: bigint;
}

export interface OffExchangeCompositionResponse {
  rows: OffExchangeCompositionRow[];
}

export interface OffExchangeCompositionRow {
  date: string;
  category: string;
  volume: number;
  notional: number;
  tradeCount: bigint;
  shareOfOffExchangeNotional: number;
}

function createBaseBarsResponse(): BarsResponse {
  return { priceScale: 0, completeThroughMs: undefined, priorCloseScaled: undefined, bars: [], cursor: "" };
}

export const BarsResponse: MessageFns<BarsResponse> = {
  encode(message: BarsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.priceScale !== 0) {
      writer.uint32(8).uint32(message.priceScale);
    }
    if (message.completeThroughMs !== undefined) {
      if (BigInt.asUintN(64, message.completeThroughMs) !== message.completeThroughMs) {
        throw new globalThis.Error("value provided for field message.completeThroughMs of type uint64 too large");
      }
      writer.uint32(16).uint64(message.completeThroughMs);
    }
    if (message.priorCloseScaled !== undefined) {
      writer.uint32(24).sint32(message.priorCloseScaled);
    }
    for (const v of message.bars) {
      Bar.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.cursor !== "") {
      writer.uint32(42).string(message.cursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BarsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBarsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.priceScale = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.completeThroughMs = reader.uint64() as bigint;
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.priorCloseScaled = reader.sint32();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.bars.push(Bar.decode(reader, reader.uint32()));
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.cursor = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<BarsResponse>): BarsResponse {
    return BarsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BarsResponse>): BarsResponse {
    const message = createBaseBarsResponse();
    message.priceScale = object.priceScale ?? 0;
    message.completeThroughMs = (object.completeThroughMs !== undefined && object.completeThroughMs !== null)
      ? BigInt(object.completeThroughMs)
      : undefined;
    message.priorCloseScaled = object.priorCloseScaled ?? undefined;
    message.bars = object.bars?.map((e) => Bar.fromPartial(e)) || [];
    message.cursor = object.cursor ?? "";
    return message;
  },
};

function createBaseBar(): Bar {
  return { tsMs: 0n, o: 0, h: 0, l: 0, c: 0, v: undefined, vwap: undefined, n: undefined };
}

export const Bar: MessageFns<Bar> = {
  encode(message: Bar, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.o !== 0) {
      writer.uint32(16).sint32(message.o);
    }
    if (message.h !== 0) {
      writer.uint32(24).sint32(message.h);
    }
    if (message.l !== 0) {
      writer.uint32(32).sint32(message.l);
    }
    if (message.c !== 0) {
      writer.uint32(40).sint32(message.c);
    }
    if (message.v !== undefined) {
      writer.uint32(48).uint32(message.v);
    }
    if (message.vwap !== undefined) {
      writer.uint32(56).sint32(message.vwap);
    }
    if (message.n !== undefined) {
      writer.uint32(64).uint32(message.n);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Bar {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBar();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.o = reader.sint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.h = reader.sint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.l = reader.sint32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.c = reader.sint32();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.v = reader.uint32();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.vwap = reader.sint32();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.n = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Bar>): Bar {
    return Bar.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Bar>): Bar {
    const message = createBaseBar();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.o = object.o ?? 0;
    message.h = object.h ?? 0;
    message.l = object.l ?? 0;
    message.c = object.c ?? 0;
    message.v = object.v ?? undefined;
    message.vwap = object.vwap ?? undefined;
    message.n = object.n ?? undefined;
    return message;
  },
};

function createBaseReplayResponse(): ReplayResponse {
  return { priceScale: 0, fidelity: 0, complete: false, sources: [], ticks: [], bars: [] };
}

export const ReplayResponse: MessageFns<ReplayResponse> = {
  encode(message: ReplayResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.priceScale !== 0) {
      writer.uint32(8).uint32(message.priceScale);
    }
    if (message.fidelity !== 0) {
      writer.uint32(16).uint32(message.fidelity);
    }
    if (message.complete !== false) {
      writer.uint32(24).bool(message.complete);
    }
    for (const v of message.sources) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.ticks) {
      Tick.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.bars) {
      Bar.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplayResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReplayResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.priceScale = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.fidelity = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.complete = reader.bool();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.sources.push(reader.string());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.ticks.push(Tick.decode(reader, reader.uint32()));
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.bars.push(Bar.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<ReplayResponse>): ReplayResponse {
    return ReplayResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReplayResponse>): ReplayResponse {
    const message = createBaseReplayResponse();
    message.priceScale = object.priceScale ?? 0;
    message.fidelity = object.fidelity ?? 0;
    message.complete = object.complete ?? false;
    message.sources = object.sources?.map((e) => e) || [];
    message.ticks = object.ticks?.map((e) => Tick.fromPartial(e)) || [];
    message.bars = object.bars?.map((e) => Bar.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTick(): Tick {
  return { tsMs: 0n, priceScaled: 0, sourceId: 0, seq: 0n };
}

export const Tick: MessageFns<Tick> = {
  encode(message: Tick, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.priceScaled !== 0) {
      writer.uint32(16).sint32(message.priceScaled);
    }
    if (message.sourceId !== 0) {
      writer.uint32(24).uint32(message.sourceId);
    }
    if (message.seq !== 0n) {
      if (BigInt.asUintN(64, message.seq) !== message.seq) {
        throw new globalThis.Error("value provided for field message.seq of type uint64 too large");
      }
      writer.uint32(32).uint64(message.seq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tick {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTick();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.priceScaled = reader.sint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.sourceId = reader.uint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.seq = reader.uint64() as bigint;
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Tick>): Tick {
    return Tick.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Tick>): Tick {
    const message = createBaseTick();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.priceScaled = object.priceScaled ?? 0;
    message.sourceId = object.sourceId ?? 0;
    message.seq = (object.seq !== undefined && object.seq !== null) ? BigInt(object.seq) : 0n;
    return message;
  },
};

function createBaseGexGridResponse(): GexGridResponse {
  return {
    capturedAtMs: undefined,
    spot: undefined,
    priorCloseSpot: undefined,
    netGex: 0,
    netGexShares: undefined,
    flipPoint: undefined,
    maxAbsGex: 0,
    maxAbsGexShares: undefined,
    adhoc: false,
    rows: [],
  };
}

export const GexGridResponse: MessageFns<GexGridResponse> = {
  encode(message: GexGridResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capturedAtMs !== undefined) {
      if (BigInt.asUintN(64, message.capturedAtMs) !== message.capturedAtMs) {
        throw new globalThis.Error("value provided for field message.capturedAtMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.capturedAtMs);
    }
    if (message.spot !== undefined) {
      writer.uint32(17).double(message.spot);
    }
    if (message.priorCloseSpot !== undefined) {
      writer.uint32(25).double(message.priorCloseSpot);
    }
    if (message.netGex !== 0) {
      writer.uint32(33).double(message.netGex);
    }
    if (message.netGexShares !== undefined) {
      writer.uint32(73).double(message.netGexShares);
    }
    if (message.flipPoint !== undefined) {
      writer.uint32(41).double(message.flipPoint);
    }
    if (message.maxAbsGex !== 0) {
      writer.uint32(49).double(message.maxAbsGex);
    }
    if (message.maxAbsGexShares !== undefined) {
      writer.uint32(81).double(message.maxAbsGexShares);
    }
    if (message.adhoc !== false) {
      writer.uint32(56).bool(message.adhoc);
    }
    for (const v of message.rows) {
      GexGridRow.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GexGridResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGexGridResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.capturedAtMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.spot = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.priorCloseSpot = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.netGex = reader.double();
            continue;
          }
          case 9: {
            if (tag !== 73) {
              break;
            }

            message.netGexShares = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.flipPoint = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.maxAbsGex = reader.double();
            continue;
          }
          case 10: {
            if (tag !== 81) {
              break;
            }

            message.maxAbsGexShares = reader.double();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.adhoc = reader.bool();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.rows.push(GexGridRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<GexGridResponse>): GexGridResponse {
    return GexGridResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GexGridResponse>): GexGridResponse {
    const message = createBaseGexGridResponse();
    message.capturedAtMs = (object.capturedAtMs !== undefined && object.capturedAtMs !== null)
      ? BigInt(object.capturedAtMs)
      : undefined;
    message.spot = object.spot ?? undefined;
    message.priorCloseSpot = object.priorCloseSpot ?? undefined;
    message.netGex = object.netGex ?? 0;
    message.netGexShares = object.netGexShares ?? undefined;
    message.flipPoint = object.flipPoint ?? undefined;
    message.maxAbsGex = object.maxAbsGex ?? 0;
    message.maxAbsGexShares = object.maxAbsGexShares ?? undefined;
    message.adhoc = object.adhoc ?? false;
    message.rows = object.rows?.map((e) => GexGridRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGexGridRow(): GexGridRow {
  return {
    strikeThousandths: 0n,
    gex: 0,
    gexShares: undefined,
    gex0dte: undefined,
    gex0dteShares: undefined,
    callOi: undefined,
    putOi: undefined,
    deltaAdj: undefined,
    deltaAdjShares: undefined,
    expiryEpochDay: undefined,
  };
}

export const GexGridRow: MessageFns<GexGridRow> = {
  encode(message: GexGridRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.strikeThousandths !== 0n) {
      if (BigInt.asIntN(64, message.strikeThousandths) !== message.strikeThousandths) {
        throw new globalThis.Error("value provided for field message.strikeThousandths of type int64 too large");
      }
      writer.uint32(8).int64(message.strikeThousandths);
    }
    if (message.gex !== 0) {
      writer.uint32(17).double(message.gex);
    }
    if (message.gexShares !== undefined) {
      writer.uint32(65).double(message.gexShares);
    }
    if (message.gex0dte !== undefined) {
      writer.uint32(25).double(message.gex0dte);
    }
    if (message.gex0dteShares !== undefined) {
      writer.uint32(73).double(message.gex0dteShares);
    }
    if (message.callOi !== undefined) {
      writer.uint32(32).int32(message.callOi);
    }
    if (message.putOi !== undefined) {
      writer.uint32(40).int32(message.putOi);
    }
    if (message.deltaAdj !== undefined) {
      writer.uint32(49).double(message.deltaAdj);
    }
    if (message.deltaAdjShares !== undefined) {
      writer.uint32(81).double(message.deltaAdjShares);
    }
    if (message.expiryEpochDay !== undefined) {
      writer.uint32(56).int32(message.expiryEpochDay);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GexGridRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGexGridRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.strikeThousandths = reader.int64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.gex = reader.double();
            continue;
          }
          case 8: {
            if (tag !== 65) {
              break;
            }

            message.gexShares = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.gex0dte = reader.double();
            continue;
          }
          case 9: {
            if (tag !== 73) {
              break;
            }

            message.gex0dteShares = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.callOi = reader.int32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.putOi = reader.int32();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.deltaAdj = reader.double();
            continue;
          }
          case 10: {
            if (tag !== 81) {
              break;
            }

            message.deltaAdjShares = reader.double();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.expiryEpochDay = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<GexGridRow>): GexGridRow {
    return GexGridRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GexGridRow>): GexGridRow {
    const message = createBaseGexGridRow();
    message.strikeThousandths = (object.strikeThousandths !== undefined && object.strikeThousandths !== null)
      ? BigInt(object.strikeThousandths)
      : 0n;
    message.gex = object.gex ?? 0;
    message.gexShares = object.gexShares ?? undefined;
    message.gex0dte = object.gex0dte ?? undefined;
    message.gex0dteShares = object.gex0dteShares ?? undefined;
    message.callOi = object.callOi ?? undefined;
    message.putOi = object.putOi ?? undefined;
    message.deltaAdj = object.deltaAdj ?? undefined;
    message.deltaAdjShares = object.deltaAdjShares ?? undefined;
    message.expiryEpochDay = object.expiryEpochDay ?? undefined;
    return message;
  },
};

function createBaseChainResponse(): ChainResponse {
  return { capturedAtMs: undefined, spot: undefined, partial: false, rows: [] };
}

export const ChainResponse: MessageFns<ChainResponse> = {
  encode(message: ChainResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capturedAtMs !== undefined) {
      if (BigInt.asUintN(64, message.capturedAtMs) !== message.capturedAtMs) {
        throw new globalThis.Error("value provided for field message.capturedAtMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.capturedAtMs);
    }
    if (message.spot !== undefined) {
      writer.uint32(17).double(message.spot);
    }
    if (message.partial !== false) {
      writer.uint32(24).bool(message.partial);
    }
    for (const v of message.rows) {
      ChainRow.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChainResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.capturedAtMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.spot = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.partial = reader.bool();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.rows.push(ChainRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<ChainResponse>): ChainResponse {
    return ChainResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChainResponse>): ChainResponse {
    const message = createBaseChainResponse();
    message.capturedAtMs = (object.capturedAtMs !== undefined && object.capturedAtMs !== null)
      ? BigInt(object.capturedAtMs)
      : undefined;
    message.spot = object.spot ?? undefined;
    message.partial = object.partial ?? false;
    message.rows = object.rows?.map((e) => ChainRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChainRow(): ChainRow {
  return {
    expiryEpochDay: 0,
    right: 0,
    strikeThousandths: 0n,
    oi: undefined,
    volume: undefined,
    bid: undefined,
    ask: undefined,
    last: undefined,
    fmv: undefined,
    iv: undefined,
    delta: undefined,
    gamma: undefined,
    theta: undefined,
    vega: undefined,
    sharesPerContract: 0,
  };
}

export const ChainRow: MessageFns<ChainRow> = {
  encode(message: ChainRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiryEpochDay !== 0) {
      writer.uint32(8).int32(message.expiryEpochDay);
    }
    if (message.right !== 0) {
      writer.uint32(16).uint32(message.right);
    }
    if (message.strikeThousandths !== 0n) {
      if (BigInt.asIntN(64, message.strikeThousandths) !== message.strikeThousandths) {
        throw new globalThis.Error("value provided for field message.strikeThousandths of type int64 too large");
      }
      writer.uint32(24).int64(message.strikeThousandths);
    }
    if (message.oi !== undefined) {
      if (BigInt.asIntN(64, message.oi) !== message.oi) {
        throw new globalThis.Error("value provided for field message.oi of type int64 too large");
      }
      writer.uint32(32).int64(message.oi);
    }
    if (message.volume !== undefined) {
      if (BigInt.asIntN(64, message.volume) !== message.volume) {
        throw new globalThis.Error("value provided for field message.volume of type int64 too large");
      }
      writer.uint32(40).int64(message.volume);
    }
    if (message.bid !== undefined) {
      writer.uint32(49).double(message.bid);
    }
    if (message.ask !== undefined) {
      writer.uint32(57).double(message.ask);
    }
    if (message.last !== undefined) {
      writer.uint32(65).double(message.last);
    }
    if (message.fmv !== undefined) {
      writer.uint32(73).double(message.fmv);
    }
    if (message.iv !== undefined) {
      writer.uint32(81).double(message.iv);
    }
    if (message.delta !== undefined) {
      writer.uint32(89).double(message.delta);
    }
    if (message.gamma !== undefined) {
      writer.uint32(97).double(message.gamma);
    }
    if (message.theta !== undefined) {
      writer.uint32(105).double(message.theta);
    }
    if (message.vega !== undefined) {
      writer.uint32(113).double(message.vega);
    }
    if (message.sharesPerContract !== 0) {
      writer.uint32(120).uint32(message.sharesPerContract);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChainRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiryEpochDay = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.right = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.strikeThousandths = reader.int64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.oi = reader.int64() as bigint;
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.volume = reader.int64() as bigint;
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.bid = reader.double();
            continue;
          }
          case 7: {
            if (tag !== 57) {
              break;
            }

            message.ask = reader.double();
            continue;
          }
          case 8: {
            if (tag !== 65) {
              break;
            }

            message.last = reader.double();
            continue;
          }
          case 9: {
            if (tag !== 73) {
              break;
            }

            message.fmv = reader.double();
            continue;
          }
          case 10: {
            if (tag !== 81) {
              break;
            }

            message.iv = reader.double();
            continue;
          }
          case 11: {
            if (tag !== 89) {
              break;
            }

            message.delta = reader.double();
            continue;
          }
          case 12: {
            if (tag !== 97) {
              break;
            }

            message.gamma = reader.double();
            continue;
          }
          case 13: {
            if (tag !== 105) {
              break;
            }

            message.theta = reader.double();
            continue;
          }
          case 14: {
            if (tag !== 113) {
              break;
            }

            message.vega = reader.double();
            continue;
          }
          case 15: {
            if (tag !== 120) {
              break;
            }

            message.sharesPerContract = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<ChainRow>): ChainRow {
    return ChainRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChainRow>): ChainRow {
    const message = createBaseChainRow();
    message.expiryEpochDay = object.expiryEpochDay ?? 0;
    message.right = object.right ?? 0;
    message.strikeThousandths = (object.strikeThousandths !== undefined && object.strikeThousandths !== null)
      ? BigInt(object.strikeThousandths)
      : 0n;
    message.oi = (object.oi !== undefined && object.oi !== null) ? BigInt(object.oi) : undefined;
    message.volume = (object.volume !== undefined && object.volume !== null) ? BigInt(object.volume) : undefined;
    message.bid = object.bid ?? undefined;
    message.ask = object.ask ?? undefined;
    message.last = object.last ?? undefined;
    message.fmv = object.fmv ?? undefined;
    message.iv = object.iv ?? undefined;
    message.delta = object.delta ?? undefined;
    message.gamma = object.gamma ?? undefined;
    message.theta = object.theta ?? undefined;
    message.vega = object.vega ?? undefined;
    message.sharesPerContract = object.sharesPerContract ?? 0;
    return message;
  },
};

function createBaseOffExchangeActivityResponse(): OffExchangeActivityResponse {
  return { rows: [] };
}

export const OffExchangeActivityResponse: MessageFns<OffExchangeActivityResponse> = {
  encode(message: OffExchangeActivityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rows) {
      OffExchangeActivityRow.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeActivityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeActivityResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.rows.push(OffExchangeActivityRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeActivityResponse>): OffExchangeActivityResponse {
    return OffExchangeActivityResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeActivityResponse>): OffExchangeActivityResponse {
    const message = createBaseOffExchangeActivityResponse();
    message.rows = object.rows?.map((e) => OffExchangeActivityRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOffExchangeActivityRow(): OffExchangeActivityRow {
  return {
    date: "",
    offExchangeVolume: 0,
    notional: 0,
    tradeCount: 0n,
    averageSize: 0,
    vwap: 0,
    offExchangeShare: undefined,
    consolidatedVolume: undefined,
    consolidatedNotional: undefined,
  };
}

export const OffExchangeActivityRow: MessageFns<OffExchangeActivityRow> = {
  encode(message: OffExchangeActivityRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.offExchangeVolume !== 0) {
      writer.uint32(17).double(message.offExchangeVolume);
    }
    if (message.notional !== 0) {
      writer.uint32(25).double(message.notional);
    }
    if (message.tradeCount !== 0n) {
      if (BigInt.asUintN(64, message.tradeCount) !== message.tradeCount) {
        throw new globalThis.Error("value provided for field message.tradeCount of type uint64 too large");
      }
      writer.uint32(32).uint64(message.tradeCount);
    }
    if (message.averageSize !== 0) {
      writer.uint32(41).double(message.averageSize);
    }
    if (message.vwap !== 0) {
      writer.uint32(49).double(message.vwap);
    }
    if (message.offExchangeShare !== undefined) {
      writer.uint32(57).double(message.offExchangeShare);
    }
    if (message.consolidatedVolume !== undefined) {
      writer.uint32(65).double(message.consolidatedVolume);
    }
    if (message.consolidatedNotional !== undefined) {
      writer.uint32(73).double(message.consolidatedNotional);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeActivityRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeActivityRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.date = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.offExchangeVolume = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.notional = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.tradeCount = reader.uint64() as bigint;
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.averageSize = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.vwap = reader.double();
            continue;
          }
          case 7: {
            if (tag !== 57) {
              break;
            }

            message.offExchangeShare = reader.double();
            continue;
          }
          case 8: {
            if (tag !== 65) {
              break;
            }

            message.consolidatedVolume = reader.double();
            continue;
          }
          case 9: {
            if (tag !== 73) {
              break;
            }

            message.consolidatedNotional = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeActivityRow>): OffExchangeActivityRow {
    return OffExchangeActivityRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeActivityRow>): OffExchangeActivityRow {
    const message = createBaseOffExchangeActivityRow();
    message.date = object.date ?? "";
    message.offExchangeVolume = object.offExchangeVolume ?? 0;
    message.notional = object.notional ?? 0;
    message.tradeCount = (object.tradeCount !== undefined && object.tradeCount !== null)
      ? BigInt(object.tradeCount)
      : 0n;
    message.averageSize = object.averageSize ?? 0;
    message.vwap = object.vwap ?? 0;
    message.offExchangeShare = object.offExchangeShare ?? undefined;
    message.consolidatedVolume = object.consolidatedVolume ?? undefined;
    message.consolidatedNotional = object.consolidatedNotional ?? undefined;
    return message;
  },
};

function createBaseOffExchangeConcentrationResponse(): OffExchangeConcentrationResponse {
  return { rows: [] };
}

export const OffExchangeConcentrationResponse: MessageFns<OffExchangeConcentrationResponse> = {
  encode(message: OffExchangeConcentrationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rows) {
      OffExchangeConcentrationRow.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeConcentrationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeConcentrationResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.rows.push(OffExchangeConcentrationRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeConcentrationResponse>): OffExchangeConcentrationResponse {
    return OffExchangeConcentrationResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeConcentrationResponse>): OffExchangeConcentrationResponse {
    const message = createBaseOffExchangeConcentrationResponse();
    message.rows = object.rows?.map((e) => OffExchangeConcentrationRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOffExchangeConcentrationRow(): OffExchangeConcentrationRow {
  return {
    date: "",
    bucketMidpoint: 0,
    bucketWidth: 0,
    volume: 0,
    notional: 0,
    tradeCount: 0n,
    distinctSessions: 0,
    rankScore: 0,
    rank: 0,
    bucketCount: 0,
    distanceBps: undefined,
    lookbackSessions: 0,
  };
}

export const OffExchangeConcentrationRow: MessageFns<OffExchangeConcentrationRow> = {
  encode(message: OffExchangeConcentrationRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.bucketMidpoint !== 0) {
      writer.uint32(17).double(message.bucketMidpoint);
    }
    if (message.bucketWidth !== 0) {
      writer.uint32(25).double(message.bucketWidth);
    }
    if (message.volume !== 0) {
      writer.uint32(33).double(message.volume);
    }
    if (message.notional !== 0) {
      writer.uint32(41).double(message.notional);
    }
    if (message.tradeCount !== 0n) {
      if (BigInt.asUintN(64, message.tradeCount) !== message.tradeCount) {
        throw new globalThis.Error("value provided for field message.tradeCount of type uint64 too large");
      }
      writer.uint32(48).uint64(message.tradeCount);
    }
    if (message.distinctSessions !== 0) {
      writer.uint32(56).uint32(message.distinctSessions);
    }
    if (message.rankScore !== 0) {
      writer.uint32(65).double(message.rankScore);
    }
    if (message.rank !== 0) {
      writer.uint32(72).uint32(message.rank);
    }
    if (message.bucketCount !== 0) {
      writer.uint32(80).uint32(message.bucketCount);
    }
    if (message.distanceBps !== undefined) {
      writer.uint32(89).double(message.distanceBps);
    }
    if (message.lookbackSessions !== 0) {
      writer.uint32(96).uint32(message.lookbackSessions);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeConcentrationRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeConcentrationRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.date = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.bucketMidpoint = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.bucketWidth = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.volume = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.notional = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.tradeCount = reader.uint64() as bigint;
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.distinctSessions = reader.uint32();
            continue;
          }
          case 8: {
            if (tag !== 65) {
              break;
            }

            message.rankScore = reader.double();
            continue;
          }
          case 9: {
            if (tag !== 72) {
              break;
            }

            message.rank = reader.uint32();
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.bucketCount = reader.uint32();
            continue;
          }
          case 11: {
            if (tag !== 89) {
              break;
            }

            message.distanceBps = reader.double();
            continue;
          }
          case 12: {
            if (tag !== 96) {
              break;
            }

            message.lookbackSessions = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeConcentrationRow>): OffExchangeConcentrationRow {
    return OffExchangeConcentrationRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeConcentrationRow>): OffExchangeConcentrationRow {
    const message = createBaseOffExchangeConcentrationRow();
    message.date = object.date ?? "";
    message.bucketMidpoint = object.bucketMidpoint ?? 0;
    message.bucketWidth = object.bucketWidth ?? 0;
    message.volume = object.volume ?? 0;
    message.notional = object.notional ?? 0;
    message.tradeCount = (object.tradeCount !== undefined && object.tradeCount !== null)
      ? BigInt(object.tradeCount)
      : 0n;
    message.distinctSessions = object.distinctSessions ?? 0;
    message.rankScore = object.rankScore ?? 0;
    message.rank = object.rank ?? 0;
    message.bucketCount = object.bucketCount ?? 0;
    message.distanceBps = object.distanceBps ?? undefined;
    message.lookbackSessions = object.lookbackSessions ?? 0;
    return message;
  },
};

function createBaseOffExchangeProfileResponse(): OffExchangeProfileResponse {
  return { rows: [] };
}

export const OffExchangeProfileResponse: MessageFns<OffExchangeProfileResponse> = {
  encode(message: OffExchangeProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rows) {
      OffExchangeProfileRow.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeProfileResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.rows.push(OffExchangeProfileRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeProfileResponse>): OffExchangeProfileResponse {
    return OffExchangeProfileResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeProfileResponse>): OffExchangeProfileResponse {
    const message = createBaseOffExchangeProfileResponse();
    message.rows = object.rows?.map((e) => OffExchangeProfileRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOffExchangeProfileRow(): OffExchangeProfileRow {
  return { date: "", priceThousandths: 0n, volume: 0, notional: 0, tradeCount: 0n };
}

export const OffExchangeProfileRow: MessageFns<OffExchangeProfileRow> = {
  encode(message: OffExchangeProfileRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.priceThousandths !== 0n) {
      if (BigInt.asIntN(64, message.priceThousandths) !== message.priceThousandths) {
        throw new globalThis.Error("value provided for field message.priceThousandths of type int64 too large");
      }
      writer.uint32(16).int64(message.priceThousandths);
    }
    if (message.volume !== 0) {
      writer.uint32(25).double(message.volume);
    }
    if (message.notional !== 0) {
      writer.uint32(33).double(message.notional);
    }
    if (message.tradeCount !== 0n) {
      if (BigInt.asUintN(64, message.tradeCount) !== message.tradeCount) {
        throw new globalThis.Error("value provided for field message.tradeCount of type uint64 too large");
      }
      writer.uint32(40).uint64(message.tradeCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeProfileRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeProfileRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.date = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.priceThousandths = reader.int64() as bigint;
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.volume = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.notional = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.tradeCount = reader.uint64() as bigint;
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeProfileRow>): OffExchangeProfileRow {
    return OffExchangeProfileRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeProfileRow>): OffExchangeProfileRow {
    const message = createBaseOffExchangeProfileRow();
    message.date = object.date ?? "";
    message.priceThousandths = (object.priceThousandths !== undefined && object.priceThousandths !== null)
      ? BigInt(object.priceThousandths)
      : 0n;
    message.volume = object.volume ?? 0;
    message.notional = object.notional ?? 0;
    message.tradeCount = (object.tradeCount !== undefined && object.tradeCount !== null)
      ? BigInt(object.tradeCount)
      : 0n;
    return message;
  },
};

function createBaseOffExchangeCompositionResponse(): OffExchangeCompositionResponse {
  return { rows: [] };
}

export const OffExchangeCompositionResponse: MessageFns<OffExchangeCompositionResponse> = {
  encode(message: OffExchangeCompositionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rows) {
      OffExchangeCompositionRow.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeCompositionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeCompositionResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.rows.push(OffExchangeCompositionRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeCompositionResponse>): OffExchangeCompositionResponse {
    return OffExchangeCompositionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeCompositionResponse>): OffExchangeCompositionResponse {
    const message = createBaseOffExchangeCompositionResponse();
    message.rows = object.rows?.map((e) => OffExchangeCompositionRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOffExchangeCompositionRow(): OffExchangeCompositionRow {
  return { date: "", category: "", volume: 0, notional: 0, tradeCount: 0n, shareOfOffExchangeNotional: 0 };
}

export const OffExchangeCompositionRow: MessageFns<OffExchangeCompositionRow> = {
  encode(message: OffExchangeCompositionRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.category !== "") {
      writer.uint32(18).string(message.category);
    }
    if (message.volume !== 0) {
      writer.uint32(25).double(message.volume);
    }
    if (message.notional !== 0) {
      writer.uint32(33).double(message.notional);
    }
    if (message.tradeCount !== 0n) {
      if (BigInt.asUintN(64, message.tradeCount) !== message.tradeCount) {
        throw new globalThis.Error("value provided for field message.tradeCount of type uint64 too large");
      }
      writer.uint32(40).uint64(message.tradeCount);
    }
    if (message.shareOfOffExchangeNotional !== 0) {
      writer.uint32(49).double(message.shareOfOffExchangeNotional);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffExchangeCompositionRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOffExchangeCompositionRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.date = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.category = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.volume = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.notional = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.tradeCount = reader.uint64() as bigint;
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.shareOfOffExchangeNotional = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<OffExchangeCompositionRow>): OffExchangeCompositionRow {
    return OffExchangeCompositionRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OffExchangeCompositionRow>): OffExchangeCompositionRow {
    const message = createBaseOffExchangeCompositionRow();
    message.date = object.date ?? "";
    message.category = object.category ?? "";
    message.volume = object.volume ?? 0;
    message.notional = object.notional ?? 0;
    message.tradeCount = (object.tradeCount !== undefined && object.tradeCount !== null)
      ? BigInt(object.tradeCount)
      : 0n;
    message.shareOfOffExchangeNotional = object.shareOfOffExchangeNotional ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends bigint ? string | number | bigint
  : T extends Builtin ? T : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
