// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.35.1
// source: itmatrixhq/ws/v1/wire.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "itmatrixhq.ws.v1";

/**
 * itmatrixhq.ws.v1 — PUBLIC wire schema for external WS clients.
 *
 * One protobuf schema shared by every language SDK. Control frames remain JSON
 * (protocol v2 control plane); each WS binary message is exactly one Frame.
 *
 * Conventions:
 *   - prices are sint32 scaled by PRICE_SCALE = 10000 (4 decimal places);
 *   - timestamps are epoch milliseconds UTC;
 *   - option right: 0 = call, 1 = put; expiry: days since 1970-01-01;
 *   - strikes are integer thousandths of a dollar (the OSI unit).
 */

/**
 * One WS data frame. Protobuf sessions subscribe routed, so every frame
 * carries its symbol.
 */
export interface Frame {
  symbol: string;
  trade?: Trade | undefined;
  mid?: Mid | undefined;
  barOpen?: BarOpen | undefined;
  barClose?: BarClose | undefined;
  quote?: Quote | undefined;
  spot?: Spot | undefined;
  indexValue?: IndexValue | undefined;
  gexSnap?: GexSnap | undefined;
  gexDelta?: GexDelta | undefined;
  chainSnap?: ChainSnap | undefined;
  chainDelta?: ChainDelta | undefined;
}

export interface Trade {
  tsMs: bigint;
  priceScaled: number;
  size: number;
}

export interface Mid {
  tsMs: bigint;
  midScaled: number;
}

export interface BarOpen {
  tsMs: bigint;
  openScaled: number;
}

export interface BarClose {
  tsMs: bigint;
  openScaled: number;
  highScaled: number;
  lowScaled: number;
  closeScaled: number;
  volume: number;
}

export interface Quote {
  tsMs: bigint;
  bidScaled: number;
  bidSize: number;
  askScaled: number;
  askSize: number;
}

export interface Spot {
  tsMs: bigint;
  priceScaled: number;
}

export interface IndexValue {
  tsMs: bigint;
  valueScaled: number;
}

export interface GexSnap {
  capturedAtMs: bigint;
  spot: number;
  netGex: number;
  strikes: GexStrike[];
}

export interface GexStrike {
  strikeThousandths: bigint;
  gex: number;
  callOi?: number | undefined;
  putOi?: number | undefined;
}

export interface GexDelta {
  capturedAtMs: bigint;
  strikes: GexDeltaStrike[];
}

export interface GexDeltaStrike {
  strikeThousandths: bigint;
  gex: number;
}

export interface ChainSnap {
  capturedAtMs: bigint;
  spot: number;
  rows: ChainRow[];
}

export interface ChainDelta {
  capturedAtMs: bigint;
  rows: ChainRow[];
}

export interface ChainRow {
  expiryEpochDay: number;
  /** 0 = call, 1 = put */
  right: number;
  strikeThousandths: bigint;
  bid?: number | undefined;
  ask?: number | undefined;
  iv?: number | undefined;
  oi?: number | undefined;
}

function createBaseFrame(): Frame {
  return {
    symbol: "",
    trade: undefined,
    mid: undefined,
    barOpen: undefined,
    barClose: undefined,
    quote: undefined,
    spot: undefined,
    indexValue: undefined,
    gexSnap: undefined,
    gexDelta: undefined,
    chainSnap: undefined,
    chainDelta: undefined,
  };
}

export const Frame: MessageFns<Frame> = {
  encode(message: Frame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.trade !== undefined) {
      Trade.encode(message.trade, writer.uint32(82).fork()).join();
    }
    if (message.mid !== undefined) {
      Mid.encode(message.mid, writer.uint32(90).fork()).join();
    }
    if (message.barOpen !== undefined) {
      BarOpen.encode(message.barOpen, writer.uint32(98).fork()).join();
    }
    if (message.barClose !== undefined) {
      BarClose.encode(message.barClose, writer.uint32(106).fork()).join();
    }
    if (message.quote !== undefined) {
      Quote.encode(message.quote, writer.uint32(114).fork()).join();
    }
    if (message.spot !== undefined) {
      Spot.encode(message.spot, writer.uint32(122).fork()).join();
    }
    if (message.indexValue !== undefined) {
      IndexValue.encode(message.indexValue, writer.uint32(130).fork()).join();
    }
    if (message.gexSnap !== undefined) {
      GexSnap.encode(message.gexSnap, writer.uint32(138).fork()).join();
    }
    if (message.gexDelta !== undefined) {
      GexDelta.encode(message.gexDelta, writer.uint32(146).fork()).join();
    }
    if (message.chainSnap !== undefined) {
      ChainSnap.encode(message.chainSnap, writer.uint32(154).fork()).join();
    }
    if (message.chainDelta !== undefined) {
      ChainDelta.encode(message.chainDelta, writer.uint32(162).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Frame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFrame();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.symbol = reader.string();
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.trade = Trade.decode(reader, reader.uint32());
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.mid = Mid.decode(reader, reader.uint32());
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.barOpen = BarOpen.decode(reader, reader.uint32());
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.barClose = BarClose.decode(reader, reader.uint32());
            continue;
          }
          case 14: {
            if (tag !== 114) {
              break;
            }

            message.quote = Quote.decode(reader, reader.uint32());
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.spot = Spot.decode(reader, reader.uint32());
            continue;
          }
          case 16: {
            if (tag !== 130) {
              break;
            }

            message.indexValue = IndexValue.decode(reader, reader.uint32());
            continue;
          }
          case 17: {
            if (tag !== 138) {
              break;
            }

            message.gexSnap = GexSnap.decode(reader, reader.uint32());
            continue;
          }
          case 18: {
            if (tag !== 146) {
              break;
            }

            message.gexDelta = GexDelta.decode(reader, reader.uint32());
            continue;
          }
          case 19: {
            if (tag !== 154) {
              break;
            }

            message.chainSnap = ChainSnap.decode(reader, reader.uint32());
            continue;
          }
          case 20: {
            if (tag !== 162) {
              break;
            }

            message.chainDelta = ChainDelta.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Frame>): Frame {
    return Frame.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Frame>): Frame {
    const message = createBaseFrame();
    message.symbol = object.symbol ?? "";
    message.trade = (object.trade !== undefined && object.trade !== null) ? Trade.fromPartial(object.trade) : undefined;
    message.mid = (object.mid !== undefined && object.mid !== null) ? Mid.fromPartial(object.mid) : undefined;
    message.barOpen = (object.barOpen !== undefined && object.barOpen !== null)
      ? BarOpen.fromPartial(object.barOpen)
      : undefined;
    message.barClose = (object.barClose !== undefined && object.barClose !== null)
      ? BarClose.fromPartial(object.barClose)
      : undefined;
    message.quote = (object.quote !== undefined && object.quote !== null) ? Quote.fromPartial(object.quote) : undefined;
    message.spot = (object.spot !== undefined && object.spot !== null) ? Spot.fromPartial(object.spot) : undefined;
    message.indexValue = (object.indexValue !== undefined && object.indexValue !== null)
      ? IndexValue.fromPartial(object.indexValue)
      : undefined;
    message.gexSnap = (object.gexSnap !== undefined && object.gexSnap !== null)
      ? GexSnap.fromPartial(object.gexSnap)
      : undefined;
    message.gexDelta = (object.gexDelta !== undefined && object.gexDelta !== null)
      ? GexDelta.fromPartial(object.gexDelta)
      : undefined;
    message.chainSnap = (object.chainSnap !== undefined && object.chainSnap !== null)
      ? ChainSnap.fromPartial(object.chainSnap)
      : undefined;
    message.chainDelta = (object.chainDelta !== undefined && object.chainDelta !== null)
      ? ChainDelta.fromPartial(object.chainDelta)
      : undefined;
    return message;
  },
};

function createBaseTrade(): Trade {
  return { tsMs: 0n, priceScaled: 0, size: 0 };
}

export const Trade: MessageFns<Trade> = {
  encode(message: Trade, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.priceScaled !== 0) {
      writer.uint32(16).sint32(message.priceScaled);
    }
    if (message.size !== 0) {
      writer.uint32(24).uint32(message.size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trade {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTrade();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.priceScaled = reader.sint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.size = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Trade>): Trade {
    return Trade.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Trade>): Trade {
    const message = createBaseTrade();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.priceScaled = object.priceScaled ?? 0;
    message.size = object.size ?? 0;
    return message;
  },
};

function createBaseMid(): Mid {
  return { tsMs: 0n, midScaled: 0 };
}

export const Mid: MessageFns<Mid> = {
  encode(message: Mid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.midScaled !== 0) {
      writer.uint32(16).sint32(message.midScaled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Mid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMid();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.midScaled = reader.sint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Mid>): Mid {
    return Mid.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Mid>): Mid {
    const message = createBaseMid();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.midScaled = object.midScaled ?? 0;
    return message;
  },
};

function createBaseBarOpen(): BarOpen {
  return { tsMs: 0n, openScaled: 0 };
}

export const BarOpen: MessageFns<BarOpen> = {
  encode(message: BarOpen, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.openScaled !== 0) {
      writer.uint32(16).sint32(message.openScaled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BarOpen {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBarOpen();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.openScaled = reader.sint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<BarOpen>): BarOpen {
    return BarOpen.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BarOpen>): BarOpen {
    const message = createBaseBarOpen();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.openScaled = object.openScaled ?? 0;
    return message;
  },
};

function createBaseBarClose(): BarClose {
  return { tsMs: 0n, openScaled: 0, highScaled: 0, lowScaled: 0, closeScaled: 0, volume: 0 };
}

export const BarClose: MessageFns<BarClose> = {
  encode(message: BarClose, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.openScaled !== 0) {
      writer.uint32(16).sint32(message.openScaled);
    }
    if (message.highScaled !== 0) {
      writer.uint32(24).sint32(message.highScaled);
    }
    if (message.lowScaled !== 0) {
      writer.uint32(32).sint32(message.lowScaled);
    }
    if (message.closeScaled !== 0) {
      writer.uint32(40).sint32(message.closeScaled);
    }
    if (message.volume !== 0) {
      writer.uint32(48).uint32(message.volume);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BarClose {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBarClose();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.openScaled = reader.sint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.highScaled = reader.sint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.lowScaled = reader.sint32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.closeScaled = reader.sint32();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.volume = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<BarClose>): BarClose {
    return BarClose.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BarClose>): BarClose {
    const message = createBaseBarClose();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.openScaled = object.openScaled ?? 0;
    message.highScaled = object.highScaled ?? 0;
    message.lowScaled = object.lowScaled ?? 0;
    message.closeScaled = object.closeScaled ?? 0;
    message.volume = object.volume ?? 0;
    return message;
  },
};

function createBaseQuote(): Quote {
  return { tsMs: 0n, bidScaled: 0, bidSize: 0, askScaled: 0, askSize: 0 };
}

export const Quote: MessageFns<Quote> = {
  encode(message: Quote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.bidScaled !== 0) {
      writer.uint32(16).sint32(message.bidScaled);
    }
    if (message.bidSize !== 0) {
      writer.uint32(24).uint32(message.bidSize);
    }
    if (message.askScaled !== 0) {
      writer.uint32(32).sint32(message.askScaled);
    }
    if (message.askSize !== 0) {
      writer.uint32(40).uint32(message.askSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Quote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseQuote();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.bidScaled = reader.sint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.bidSize = reader.uint32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.askScaled = reader.sint32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.askSize = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Quote>): Quote {
    return Quote.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Quote>): Quote {
    const message = createBaseQuote();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.bidScaled = object.bidScaled ?? 0;
    message.bidSize = object.bidSize ?? 0;
    message.askScaled = object.askScaled ?? 0;
    message.askSize = object.askSize ?? 0;
    return message;
  },
};

function createBaseSpot(): Spot {
  return { tsMs: 0n, priceScaled: 0 };
}

export const Spot: MessageFns<Spot> = {
  encode(message: Spot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.priceScaled !== 0) {
      writer.uint32(16).sint32(message.priceScaled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Spot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSpot();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.priceScaled = reader.sint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<Spot>): Spot {
    return Spot.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Spot>): Spot {
    const message = createBaseSpot();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.priceScaled = object.priceScaled ?? 0;
    return message;
  },
};

function createBaseIndexValue(): IndexValue {
  return { tsMs: 0n, valueScaled: 0 };
}

export const IndexValue: MessageFns<IndexValue> = {
  encode(message: IndexValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tsMs !== 0n) {
      if (BigInt.asUintN(64, message.tsMs) !== message.tsMs) {
        throw new globalThis.Error("value provided for field message.tsMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.tsMs);
    }
    if (message.valueScaled !== 0) {
      writer.uint32(16).sint32(message.valueScaled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseIndexValue();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.tsMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.valueScaled = reader.sint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<IndexValue>): IndexValue {
    return IndexValue.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IndexValue>): IndexValue {
    const message = createBaseIndexValue();
    message.tsMs = (object.tsMs !== undefined && object.tsMs !== null) ? BigInt(object.tsMs) : 0n;
    message.valueScaled = object.valueScaled ?? 0;
    return message;
  },
};

function createBaseGexSnap(): GexSnap {
  return { capturedAtMs: 0n, spot: 0, netGex: 0, strikes: [] };
}

export const GexSnap: MessageFns<GexSnap> = {
  encode(message: GexSnap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capturedAtMs !== 0n) {
      if (BigInt.asUintN(64, message.capturedAtMs) !== message.capturedAtMs) {
        throw new globalThis.Error("value provided for field message.capturedAtMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.capturedAtMs);
    }
    if (message.spot !== 0) {
      writer.uint32(17).double(message.spot);
    }
    if (message.netGex !== 0) {
      writer.uint32(25).double(message.netGex);
    }
    for (const v of message.strikes) {
      GexStrike.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GexSnap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGexSnap();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.capturedAtMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.spot = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.netGex = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.strikes.push(GexStrike.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<GexSnap>): GexSnap {
    return GexSnap.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GexSnap>): GexSnap {
    const message = createBaseGexSnap();
    message.capturedAtMs = (object.capturedAtMs !== undefined && object.capturedAtMs !== null)
      ? BigInt(object.capturedAtMs)
      : 0n;
    message.spot = object.spot ?? 0;
    message.netGex = object.netGex ?? 0;
    message.strikes = object.strikes?.map((e) => GexStrike.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGexStrike(): GexStrike {
  return { strikeThousandths: 0n, gex: 0, callOi: undefined, putOi: undefined };
}

export const GexStrike: MessageFns<GexStrike> = {
  encode(message: GexStrike, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.strikeThousandths !== 0n) {
      if (BigInt.asIntN(64, message.strikeThousandths) !== message.strikeThousandths) {
        throw new globalThis.Error("value provided for field message.strikeThousandths of type int64 too large");
      }
      writer.uint32(8).int64(message.strikeThousandths);
    }
    if (message.gex !== 0) {
      writer.uint32(17).double(message.gex);
    }
    if (message.callOi !== undefined) {
      writer.uint32(24).int32(message.callOi);
    }
    if (message.putOi !== undefined) {
      writer.uint32(32).int32(message.putOi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GexStrike {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGexStrike();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.strikeThousandths = reader.int64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.gex = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.callOi = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.putOi = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<GexStrike>): GexStrike {
    return GexStrike.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GexStrike>): GexStrike {
    const message = createBaseGexStrike();
    message.strikeThousandths = (object.strikeThousandths !== undefined && object.strikeThousandths !== null)
      ? BigInt(object.strikeThousandths)
      : 0n;
    message.gex = object.gex ?? 0;
    message.callOi = object.callOi ?? undefined;
    message.putOi = object.putOi ?? undefined;
    return message;
  },
};

function createBaseGexDelta(): GexDelta {
  return { capturedAtMs: 0n, strikes: [] };
}

export const GexDelta: MessageFns<GexDelta> = {
  encode(message: GexDelta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capturedAtMs !== 0n) {
      if (BigInt.asUintN(64, message.capturedAtMs) !== message.capturedAtMs) {
        throw new globalThis.Error("value provided for field message.capturedAtMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.capturedAtMs);
    }
    for (const v of message.strikes) {
      GexDeltaStrike.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GexDelta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGexDelta();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.capturedAtMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.strikes.push(GexDeltaStrike.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<GexDelta>): GexDelta {
    return GexDelta.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GexDelta>): GexDelta {
    const message = createBaseGexDelta();
    message.capturedAtMs = (object.capturedAtMs !== undefined && object.capturedAtMs !== null)
      ? BigInt(object.capturedAtMs)
      : 0n;
    message.strikes = object.strikes?.map((e) => GexDeltaStrike.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGexDeltaStrike(): GexDeltaStrike {
  return { strikeThousandths: 0n, gex: 0 };
}

export const GexDeltaStrike: MessageFns<GexDeltaStrike> = {
  encode(message: GexDeltaStrike, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.strikeThousandths !== 0n) {
      if (BigInt.asIntN(64, message.strikeThousandths) !== message.strikeThousandths) {
        throw new globalThis.Error("value provided for field message.strikeThousandths of type int64 too large");
      }
      writer.uint32(8).int64(message.strikeThousandths);
    }
    if (message.gex !== 0) {
      writer.uint32(17).double(message.gex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GexDeltaStrike {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGexDeltaStrike();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.strikeThousandths = reader.int64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.gex = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<GexDeltaStrike>): GexDeltaStrike {
    return GexDeltaStrike.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GexDeltaStrike>): GexDeltaStrike {
    const message = createBaseGexDeltaStrike();
    message.strikeThousandths = (object.strikeThousandths !== undefined && object.strikeThousandths !== null)
      ? BigInt(object.strikeThousandths)
      : 0n;
    message.gex = object.gex ?? 0;
    return message;
  },
};

function createBaseChainSnap(): ChainSnap {
  return { capturedAtMs: 0n, spot: 0, rows: [] };
}

export const ChainSnap: MessageFns<ChainSnap> = {
  encode(message: ChainSnap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capturedAtMs !== 0n) {
      if (BigInt.asUintN(64, message.capturedAtMs) !== message.capturedAtMs) {
        throw new globalThis.Error("value provided for field message.capturedAtMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.capturedAtMs);
    }
    if (message.spot !== 0) {
      writer.uint32(17).double(message.spot);
    }
    for (const v of message.rows) {
      ChainRow.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainSnap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChainSnap();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.capturedAtMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.spot = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.rows.push(ChainRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<ChainSnap>): ChainSnap {
    return ChainSnap.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChainSnap>): ChainSnap {
    const message = createBaseChainSnap();
    message.capturedAtMs = (object.capturedAtMs !== undefined && object.capturedAtMs !== null)
      ? BigInt(object.capturedAtMs)
      : 0n;
    message.spot = object.spot ?? 0;
    message.rows = object.rows?.map((e) => ChainRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChainDelta(): ChainDelta {
  return { capturedAtMs: 0n, rows: [] };
}

export const ChainDelta: MessageFns<ChainDelta> = {
  encode(message: ChainDelta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capturedAtMs !== 0n) {
      if (BigInt.asUintN(64, message.capturedAtMs) !== message.capturedAtMs) {
        throw new globalThis.Error("value provided for field message.capturedAtMs of type uint64 too large");
      }
      writer.uint32(8).uint64(message.capturedAtMs);
    }
    for (const v of message.rows) {
      ChainRow.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainDelta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChainDelta();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.capturedAtMs = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.rows.push(ChainRow.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<ChainDelta>): ChainDelta {
    return ChainDelta.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChainDelta>): ChainDelta {
    const message = createBaseChainDelta();
    message.capturedAtMs = (object.capturedAtMs !== undefined && object.capturedAtMs !== null)
      ? BigInt(object.capturedAtMs)
      : 0n;
    message.rows = object.rows?.map((e) => ChainRow.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChainRow(): ChainRow {
  return {
    expiryEpochDay: 0,
    right: 0,
    strikeThousandths: 0n,
    bid: undefined,
    ask: undefined,
    iv: undefined,
    oi: undefined,
  };
}

export const ChainRow: MessageFns<ChainRow> = {
  encode(message: ChainRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiryEpochDay !== 0) {
      writer.uint32(8).int32(message.expiryEpochDay);
    }
    if (message.right !== 0) {
      writer.uint32(16).uint32(message.right);
    }
    if (message.strikeThousandths !== 0n) {
      if (BigInt.asIntN(64, message.strikeThousandths) !== message.strikeThousandths) {
        throw new globalThis.Error("value provided for field message.strikeThousandths of type int64 too large");
      }
      writer.uint32(24).int64(message.strikeThousandths);
    }
    if (message.bid !== undefined) {
      writer.uint32(33).double(message.bid);
    }
    if (message.ask !== undefined) {
      writer.uint32(41).double(message.ask);
    }
    if (message.iv !== undefined) {
      writer.uint32(49).double(message.iv);
    }
    if (message.oi !== undefined) {
      writer.uint32(56).int32(message.oi);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseChainRow();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiryEpochDay = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.right = reader.uint32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.strikeThousandths = reader.int64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.bid = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.ask = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.iv = reader.double();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.oi = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create(base?: DeepPartial<ChainRow>): ChainRow {
    return ChainRow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChainRow>): ChainRow {
    const message = createBaseChainRow();
    message.expiryEpochDay = object.expiryEpochDay ?? 0;
    message.right = object.right ?? 0;
    message.strikeThousandths = (object.strikeThousandths !== undefined && object.strikeThousandths !== null)
      ? BigInt(object.strikeThousandths)
      : 0n;
    message.bid = object.bid ?? undefined;
    message.ask = object.ask ?? undefined;
    message.iv = object.iv ?? undefined;
    message.oi = object.oi ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends bigint ? string | number | bigint
  : T extends Builtin ? T : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
